version: "2.0"

services:
    application:
        image: debian:jessie
        volumes:
            - ./project/application:/var/www/lazy-time
        tty: true

    nodejs:
        build: docker/nodejs
        restart: always
        container_name: lazy-time_nodejs
        volumes_from:
            - application
        stdin_open: true
        tty: true

    nginx:
        build: docker/nginx
        restart: always
        volumes_from:
            - application
